import 'dart:math';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/app_user.dart';
import 'local_repository.dart';

class AuthRepository {
  AuthRepository(this.local,{this.client}); final LocalRepository local; final SupabaseClient? client; final Map<String,String> _smsCodes={};
  bool get serverEnabled=>client!=null; String normalizePhone(String v)=>v.replaceAll(RegExp(r'[^0-9]'),''); String toE164(String v){final n=normalizePhone(v);if(n.startsWith('82'))return '+$n';if(n.startsWith('0'))return '+82${n.substring(1)}';return '+82$n';} String loginEmail(String id)=>'${id.trim().toLowerCase()}@login.campingcarroadmap.invalid'; bool validPassword(String v)=>v.length>=8&&v.length<=20&&RegExp(r'[A-Za-z]').hasMatch(v)&&RegExp(r'[0-9]').hasMatch(v)&&RegExp(r'[^A-Za-z0-9]').hasMatch(v);
  Future<String> sendMockSms(String p)async{final c=(100000+Random().nextInt(900000)).toString();_smsCodes[normalizePhone(p)]=c;return c;} bool verifySms(String p,String c)=>_smsCodes[normalizePhone(p)]==c.trim();
  Future<AppUser?> login(String userId,String password,{bool administratorMode=false})async{AppUser? u;if(!serverEnabled){for(final x in await local.users()){if(x.userId.toLowerCase()==userId.toLowerCase()&&x.password==password){u=x;break;}}if(u!=null)await local.setSession(u.userId);}else{try{final res=await client!.functions.invoke('login-by-username',body:{'username':userId.trim(),'password':password}),data=res.data;if(data is! Map||data['ok']!=true||'${data['refresh_token']??''}'.isEmpty)return null;await client!.auth.setSession('${data['refresh_token']}');u=await currentUser();final au=client!.auth.currentUser;if(au!=null){await client!.from('profiles').update({'last_seen_at':DateTime.now().toIso8601String()}).eq('id',au.id);}}catch(_){return null;}}if(u==null)return null;if(administratorMode&&!u.isAdministrator){await logout();return null;}if(!administratorMode&&u.isAdministrator){await logout();return null;}return u;}
  Future<void> logout()async{if(serverEnabled){await client!.auth.signOut();}else{await local.setSession(null);}}
  Future<void> signup(AppUser u)async{if(serverEnabled)throw UnsupportedError('서버 모드에서는 SMS 인증 회원가입을 사용합니다.');final users=await local.users();if(users.any((x)=>x.userId.toLowerCase()==u.userId.toLowerCase()))throw Exception('이미 사용 중인 아이디입니다.');if(u.nickname.trim().isEmpty)throw Exception('닉네임은 필수입니다.');users.add(u);await local.saveUsers(users);}
  String _smsError(Object? c){switch('$c'){case'too_many_requests':return'인증번호는 1분 후 다시 요청할 수 있습니다.';case'sms_send_failed':return'문자 발송에 실패했습니다. 잠시 후 다시 시도해주세요.';case'sms_not_configured':return'문자 발송 설정을 확인해주세요.';case'invalid_phone':return'휴대폰 번호를 확인해주세요.';case'invalid_otp':return'인증번호가 일치하지 않습니다.';case'otp_expired':return'인증번호 유효시간이 지났습니다. 다시 받아주세요.';case'too_many_attempts':return'인증번호 입력 횟수를 초과했습니다. 새 인증번호를 받아주세요.';case'username_taken':return'이미 사용 중인 아이디입니다.';case'phone_taken':return'이미 가입된 휴대폰 번호입니다.';default:return'처리 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요.';}}
  Future<void> beginServerSignup({required String userId,required String password,required String phone,required String nickname,String vehicleStatus='planned',String vehicleName='',int? vehicleHeightMm,String sanitation=''})async{if(!serverEnabled)return;final id=userId.trim();if(id.toLowerCase()=='administrator')throw Exception('administrator 아이디는 관리자 전용이라 일반 회원가입으로 만들 수 없습니다.');if(!RegExp(r'^[A-Za-z0-9_]{4,20}$').hasMatch(id))throw Exception('아이디는 영문/숫자/밑줄 4~20자로 입력해주세요.');if(!validPassword(password))throw Exception('비밀번호 규칙을 확인해주세요.');if(nickname.trim().isEmpty||nickname.trim().length>20)throw Exception('닉네임은 1~20자로 입력해주세요.');if(vehicleStatus=='owned'&&(vehicleName.trim().isEmpty||vehicleHeightMm==null||vehicleHeightMm<=0||sanitation.isEmpty))throw Exception('차량정보를 모두 입력해주세요.');await resendServerSignupOtp(phone);}
  Future<void> resendServerSignupOtp(String phone)async{if(!serverEnabled)return;final res=await client!.functions.invoke('send-signup-otp',body:{'phone':normalizePhone(phone)}),d=res.data;if(d is! Map||d['ok']!=true)throw Exception(_smsError(d is Map?d['error']:null));}
  Future<void> verifyServerSignupPhone({required String phone,required String token,required String userId,required String password,required String nickname,required String vehicleStatus,required String vehicleName,required int? vehicleHeightMm,required String sanitation})async{if(!serverEnabled)return;final res=await client!.functions.invoke('complete-signup',body:{'phone':normalizePhone(phone),'token':token.trim(),'userId':userId.trim(),'password':password,'nickname':nickname.trim(),'vehicleStatus':vehicleStatus,'vehicleName':vehicleName,'vehicleHeightMm':vehicleHeightMm,'sanitation':sanitation}),d=res.data;if(d is! Map||d['ok']!=true)throw Exception(_smsError(d is Map?d['error']:null));}
  Future<AppUser?> currentUser()async{if(!serverEnabled){final id=await local.sessionUserId();if(id==null)return null;for(final u in await local.users()){if(u.userId==id)return u;}return null;}final au=client!.auth.currentUser;if(au==null)return null;final row=await client!.from('profiles').select().eq('id',au.id).maybeSingle();return row==null?null:AppUser.fromJson(Map<String,dynamic>.from(row));}
  Future<void> sendRecoveryOtp(String p)async{if(serverEnabled)await client!.auth.signInWithOtp(phone:toE164(p),shouldCreateUser:false);} Future<void> verifyRecoveryOtp(String p,String t)async{if(serverEnabled)await client!.auth.verifyOTP(type:OtpType.sms,phone:toE164(p),token:t.trim());}
  Future<String?> findIdByPhone(String p)async{if(!serverEnabled){for(final u in await local.users()){if(normalizePhone(u.phone)==normalizePhone(p))return u.userId;}return null;}final u=await currentUser();return u!=null&&normalizePhone(u.phone)==normalizePhone(p)?u.userId:null;}
  Future<bool> resetPassword(String id,String p,String np)async{if(!serverEnabled){final us=await local.users();for(final u in us){if(u.userId.toLowerCase()==id.toLowerCase()&&normalizePhone(u.phone)==normalizePhone(p)){u.password=np;await local.saveUsers(us);return true;}}return false;}final u=await currentUser();if(u==null||u.userId.toLowerCase()!=id.toLowerCase()||normalizePhone(u.phone)!=normalizePhone(p))return false;await client!.auth.updateUser(UserAttributes(password:np));return true;}
  Future<bool> reauthenticatePassword(String p)async{final u=await currentUser();if(u==null)return false;if(!serverEnabled)return u.password==p;try{final r=await client!.functions.invoke('login-by-username',body:{'username':u.userId,'password':p});return r.data is Map&&r.data['ok']==true;}catch(_){return false;}}
  Future<AppUser> updateVehicle({required String status,required String name,required int? heightMm,required String sanitation})async{final p=await currentUser();if(p==null)throw Exception('로그인이 필요합니다.');p.vehicleStatus=status;p.vehicleName=name;p.vehicleHeightMm=heightMm;p.sanitationType=sanitation;if(!serverEnabled){final us=await local.users(),i=us.indexWhere((u)=>u.userId==p.userId);if(i>=0)us[i]=p;await local.saveUsers(us);return p;}await client!.from('profiles').update({'vehicle_status':status,'vehicle_name':name,'vehicle_height_mm':heightMm,'sanitation_type':sanitation}).eq('id',client!.auth.currentUser!.id);return(await currentUser())!;}
  Future<void> deleteAccount()async{if(!serverEnabled){final p=await currentUser();if(p==null)return;final us=await local.users();us.removeWhere((u)=>u.userId==p.userId);await local.saveUsers(us);await local.setSession(null);return;}final s=client!.auth.currentSession;if(s==null)throw Exception('로그인이 필요합니다.');final r=await client!.functions.invoke('delete-account',headers:{'Authorization':'Bearer ${s.accessToken}'});if(r.data is Map&&r.data['ok']!=true)throw Exception('${r.data['error']??'회원탈퇴 처리에 실패했습니다.'}');await client!.auth.signOut();}
}
