import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
class AdminManagementScreen extends StatefulWidget{const AdminManagementScreen({super.key});@override State<AdminManagementScreen> createState()=>_S();}
class _S extends State<AdminManagementScreen> with SingleTickerProviderStateMixin{
 final db=Supabase.instance.client;final memberSearch=TextEditingController();late final TabController tabs;List<Map<String,dynamic>> market=[],members=[],feedback=[],reports=[];bool loading=true;String memberQuery='';
 @override void initState(){super.initState();tabs=TabController(length:4,vsync:this);_load();}@override void dispose(){memberSearch.dispose();tabs.dispose();super.dispose();}
 Future<void> _load()async{setState(()=>loading=true);try{final a=await Future.wait([db.from('vehicle_market_listings').select().order('created_at',ascending:false),db.from('profiles').select().order('created_at',ascending:false),db.from('app_feedback').select().order('created_at',ascending:false),db.from('vehicle_market_reports').select().order('created_at',ascending:false)]);if(mounted)setState((){market=List<Map<String,dynamic>>.from(a[0]);members=List<Map<String,dynamic>>.from(a[1]);feedback=List<Map<String,dynamic>>.from(a[2]);reports=List<Map<String,dynamic>>.from(a[3]);});}finally{if(mounted)setState(()=>loading=false);}}
 String _userId(Map<String,dynamic>x)=>'${x['username']??x['user_id']??''}'.trim(),_nickname(Map<String,dynamic>x)=>'${x['nickname']??x['display_name']??''}'.trim();String _memberTitle(Map<String,dynamic>x){final a=_userId(x),b=_nickname(x);return a.isNotEmpty&&b.isNotEmpty?'$a · $b':a.isNotEmpty?a:b.isNotEmpty?b:'회원정보 없음';}String _name(dynamic id){for(final m in members){if('${m['id']}'=='$id')return _nickname(m).isEmpty?_userId(m):_nickname(m);}return'닉네임 없음';}String _dt(dynamic v){final d=DateTime.tryParse('$v')?.toLocal();return d==null?'-':d.toString().substring(0,16);}
 List<Map<String,dynamic>> get _filteredMembers{final q=memberQuery.trim().toLowerCase();if(q.isEmpty)return members;return members.where((x)=>'${_userId(x)} ${_nickname(x)}'.toLowerCase().contains(q)).toList();}
 void msg(String s)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(s)));
 Future<void> _reply(Map<String,dynamic>x)async{final c=TextEditingController(text:'${x['admin_reply']??''}');final ok=await showDialog<bool>(context:context,builder:(d)=>AlertDialog(title:Text('${x['title']}'),content:TextField(controller:c,maxLines:6,decoration:const InputDecoration(labelText:'관리자 답변',border:OutlineInputBorder()),),actions:[TextButton(onPressed:()=>Navigator.pop(d,false),child:const Text('취소')),FilledButton(onPressed:()=>Navigator.pop(d,true),child:const Text('답변 저장'))]));if(ok==true&&c.text.trim().isNotEmpty){await db.from('app_feedback').update({'admin_reply':c.text.trim(),'status':'answered','answered_at':DateTime.now().toIso8601String()}).eq('id',x['id']);await _load();}}
 Future<void> _member(Map<String,dynamic>x,String s)async{await db.from('profiles').update({'account_status':s}).eq('id',x['id']);await _load();}
 Future<void> _showMember(Map<String,dynamic>x)async{final f=<MapEntry<String,String>>[MapEntry('아이디',_userId(x)),MapEntry('닉네임',_nickname(x)),MapEntry('휴대폰','${x['phone']??''}'),MapEntry('휴대폰 인증',x['phone_verified']==true?'완료':'미인증'),MapEntry('회원상태','${x['account_status']??'active'}'),MapEntry('권한','${x['role']??'user'}'),MapEntry('차량상태','${x['vehicle_status']??''}'),MapEntry('차량명/모델','${x['vehicle_name']??''}'),MapEntry('차량높이',x['vehicle_height_mm']==null?'':'${(x['vehicle_height_mm']as num)/1000} m'),MapEntry('위생설비','${x['sanitation_type']??''}'),MapEntry('가입일',_dt(x['created_at'])),MapEntry('마지막접속일자 및 시간',_dt(x['last_seen_at']))];await showModalBottomSheet<void>(context:context,showDragHandle:true,isScrollControlled:true,builder:(c)=>SafeArea(child:SizedBox(height:MediaQuery.of(c).size.height*.78,child:Column(children:[Padding(padding:const EdgeInsets.all(16),child:Text(_memberTitle(x),style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold))),Expanded(child:ListView(children:f.map((e)=>ListTile(title:Text(e.key),subtitle:Text(e.value))).toList()))]))));}
 Widget _memberTab(){final r=_filteredMembers;return Column(children:[Padding(padding:const EdgeInsets.all(12),child:TextField(controller:memberSearch,onChanged:(v)=>setState(()=>memberQuery=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search),hintText:'아이디 · 닉네임 통합검색',border:OutlineInputBorder()))),Expanded(child:ListView.builder(itemCount:r.length,itemBuilder:(_,i){final x=r[i];return ListTile(title:Text(_memberTitle(x)),subtitle:Text('상태: ${x['account_status']??'active'}'),onTap:()=>_showMember(x),trailing:PopupMenuButton<String>(onSelected:(v)=>_member(x,v),itemBuilder:(_)=>const[PopupMenuItem(value:'active',child:Text('정상 복구')),PopupMenuItem(value:'suspended',child:Text('자격정지')),PopupMenuItem(value:'withdrawn',child:Text('탈퇴 처리'))]));}))]);}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('관리자 통합관리'),bottom:TabBar(controller:tabs,isScrollable:true,tabs:const[Tab(text:'중고매물'),Tab(text:'회원'),Tab(text:'의견'),Tab(text:'신고')])),body:loading?const Center(child:CircularProgressIndicator()):TabBarView(controller:tabs,children:[ListView.builder(itemCount:market.length,itemBuilder:(_,i){final x=market[i];return ListTile(title:Text('${x['title']}'),subtitle:Text('${x['status']=='sold'?'판매완료':'판매중'} · 등록자 ${_name(x['owner_id'])} · ${_dt(x['created_at'])}'));}),_memberTab(),ListView.builder(itemCount:feedback.length,itemBuilder:(_,i){final x=feedback[i];return ListTile(title:Text('${x['title']}'),subtitle:Text('${x['body']}\n작성자: ${_name(x['author_id'])} · 요청: ${_dt(x['created_at'])}\n${x['status']=='answered'?'답변완료':'답변대기'}'),isThreeLine:true,onTap:()=>_reply(x));}),ListView.builder(itemCount:reports.length,itemBuilder:(_,i){final x=reports[i];return ListTile(leading:const Icon(Icons.report),title:Text('매물 ${x['listing_id']}'),subtitle:Text('${x['reason']}\n신고자: ${_name(x['reporter_id'])} · 요청: ${_dt(x['created_at'])}'),isThreeLine:true,trailing:Text('${x['status']}'));})]));
}
